release ci iter 1

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,15 +1,20 @@
 name: release
 
 on:
-  push:
-    tags:
-      - "*"
+  workflow_dispatch:
+    inputs:
+      release-version:
+        description: "A valid Semver version string"
+        required: true
 
 permissions:
   contents: write
 
 jobs:
   release:
+    # Do not release if not triggered from the default branch
+    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
+
     runs-on: ubuntu-latest
     timeout-minutes: 30
 
@@ -21,7 +26,7 @@ jobs:
       - name: Checkout the code
         uses: actions/checkout@v3
 
-      - name: Setup conda
+      - name: Setup Mamba
         uses: mamba-org/provision-with-micromamba@v15
         with:
           environment-file: env.yml
@@ -29,7 +34,47 @@ jobs:
           cache-downloads: true
           cache-env: true
           extra-specs: |
-            setuptools-scm
+            pip
+            semver
+            git
+            rever==0.5.1
+            setuptools_scm
+
+      - name: Check the version is valid semver
+        run: |
+          RELEASE_VERSION="${{ inputs.release-version }}"
+
+          {
+            pysemver check $RELEASE_VERSION
+          } || {
+            echo "The version '$RELEASE_VERSION' is not a valid Semver version string."
+            echo "Please use a valid semver version string. More details at https://semver.org/"
+            echo "The release process is aborted."
+            exit 1
+          }
+
+      - name: Check the version is higher than the latest one
+        run: |
+          # Retrieve the git tags first
+          git fetch --prune --unshallow --tags &> /dev/null
+
+          RELEASE_VERSION="${{ inputs.release-version }}"
+          LATEST_VERSION=$(git describe --abbrev=0 --tags)
+
+          IS_HIGHER_VERSION=$(pysemver compare $RELEASE_VERSION $LATEST_VERSION)
+
+          if [ "$IS_HIGHER_VERSION" != "1" ]; then
+            echo "The version '$RELEASE_VERSION' is not higher than the latest version '$LATEST_VERSION'."
+            echo "The release process is aborted."
+            exit 1
+          fi
+
+      - name: Perform the release with rever
+        env:
+          # It's important to be able to allow the GA to trigger child GA such as docker image build upon a tag push.
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          rever ${{ inputs.release-version }}
 
       - name: Install library
         run: python -m pip install --no-deps .
